import Screen from "@/components/Screen";
import Colors from "@/constants/Colors";
import Icon from "../components/Icon";
import ListItem from "@/components/lists/ListItem";
import MyTextInput from "@/components/MyTextInput";
import MyPicker from "@/components/MyPicker";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import ListingsScreen from "./screens/ListingsScreen";
import { useState } from "react";
import { StyleSheet, Switch, Text, TextInput, View } from "react-native";
import WelcomeScreen from "./screens/WelcomeScreen";
import Card from "../components/Card";
import ViewImageScreen from "./screens/ViewImageScreen";
import ListingDetailsScreen from "./screens/ListingDetailsScreen";
import MessagesScreen from "./screens/MessagesScreen";
import AccountScreen from "./screens/AccountScreen";
